services:
  database:
    image: mysql:8.0
    container_name: jadda_mysql
    restart: always

    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --innodb-buffer-pool-size=128M --default-time-zone=-05:00

    environment:
      MYSQL_ROOT_PASSWORD: tu_password_secreto
      MYSQL_DATABASE: jadda_sports_db
      TZ: America/Bogota

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p\"$$MYSQL_ROOT_PASSWORD\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  backend:
    build: ./backend
    container_name: jadda_backend
    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=tu_password_secreto
      - DB_NAME=jadda_sports_db
      - TZ=America/Bogota
      - CI=true
      - DOTENV_QUIET=true

    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
      - ./frontend/public/images/productos:/app/uploads
      - ./frontend/public/images/perfiles:/app/uploads/perfiles
      - ./frontend/public/images/retos:/app/uploads/retos
      - ./frontend/public/images/usuarios:/app/uploads/usuarios
      - ./frontend/public/images/devoluciones:/app/uploads/devoluciones

    command: sh -c "pnpm install --no-frozen-lockfile && pnpm dev"

    stdin_open: true
    tty: true

    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: jadda_frontend

    ports:
      - "5173:5173"

    environment:
      - CI=true

    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules

    command: sh -c "pnpm install --no-frozen-lockfile && if [ \"$MODE\" = \"preview\" ]; then pnpm build && pnpm preview --host --port 5173; else pnpm dev --host; fi"

    stdin_open: true
    tty: true

    depends_on:
      - backend

volumes:
  backend_modules:
  frontend_modules:
  mysql_data: