services:
  database:
    image: mysql:8.0
    container_name: jadda_mysql
    restart: always

    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=128M

    environment:
      MYSQL_ROOT_PASSWORD: tu_password_secreto
      MYSQL_DATABASE: jadda_sports_db
      

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: jadda_backend

    ports:
      - "5000:5000"

    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=tu_password_secreto
      - DB_NAME=jadda_sports_db
      - CI=true
      - DOTENV_QUIET=true

    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules

    command: sh -c "pnpm install --no-frozen-lockfile && pnpm dev"

    stdin_open: true
    tty: true

    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: jadda_frontend

    ports:
      - "5173:5173"

    environment:
      - CI=true

    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules

    command: sh -c "pnpm install --no-frozen-lockfile && pnpm run dev --host"

    stdin_open: true
    tty: true

    depends_on:
      - backend

volumes:
  backend_modules:
  frontend_modules:
  mysql_data: